"""Generate world_map_data.js from World_map.xlsx (run after editing the spreadsheet).

Map grid: column B onward × row 2 onward — cell fill sets biome (legend rows 104+).
Optional: type a city name in a map cell (same cell as fill) to mark a medieval city at that tile.
City tiles have no random encounters; names show on the minimap and city icons on the painted map (see build_world_map_texture.py).
"""
import json
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "World_map.xlsx"
OUT = ROOT / "world_map_data.js"

# Only this many rows from the grid (Excel rows 2 .. 1+ROWS) are exported: game y = 0 .. ROWS-1.
# Rows below that in the sheet are treated as margin and ignored.
MAX_MAP_DATA_ROWS = 100  # last playable y index = 99


def rgb_to_hex(cell):
    fill = cell.fill
    if fill is None or fill.fill_type is None:
        return None
    fg = getattr(fill, "fgColor", None)
    if fg is None:
        return None
    rgb = getattr(fg, "rgb", None)
    if rgb is None:
        return None
    if isinstance(rgb, str):
        s = rgb.upper()
        if s.startswith("FF") and len(s) == 8:
            s = s[2:]
        if len(s) == 6:
            return "#" + s
    return None


def main():
    wb = openpyxl.load_workbook(XLSX, data_only=False)
    ws = wb.active

    hex_to_idx = {}
    biome_rows = []
    for r in range(104, 200):
        cell = ws.cell(r, 1)
        name = cell.value
        if name is None or (isinstance(name, str) and not str(name).strip()):
            break
        hx = rgb_to_hex(cell)
        if not hx:
            continue
        idx = len(hex_to_idx)
        hex_to_idx[hx] = idx
        biome_rows.append({"name": str(name).strip(), "hex": hx, "idx": idx})

    # Passable: legend order from user spec — match by hex
    IMPASSABLE = {
        "#729FCF",
        "#00E3E3",
        "#8D281E",
        "#77BC65",
        "#E16173",
        "#2A6099",
        "#0084D1",
    }
    for b in biome_rows:
        b["passable"] = b["hex"] not in IMPASSABLE

    # Build index map: hex -> idx
    idx_by_hex = {b["hex"]: b["idx"] for b in biome_rows}

    # Unknown hex fallback
    def cell_idx(r, c):
        hx = rgb_to_hex(ws.cell(r, c))
        if not hx:
            return 0
        return idx_by_hex.get(hx, 0)

    sheet_rows = ws.max_row - 1  # rows 2..max_row
    height = min(sheet_rows, MAX_MAP_DATA_ROWS)
    width = ws.max_column - 1  # cols 2..max_col
    flat = []
    city_names: dict[str, str] = {}
    for r in range(2, 2 + height):
        for c in range(2, 2 + width):
            flat.append(cell_idx(r, c))
            cell = ws.cell(r, c)
            v = cell.value
            if isinstance(v, str):
                s = v.strip()
                if s:
                    gx = c - 2
                    gy = r - 2
                    city_names[f"{gx},{gy}"] = s

    js = []
    js.append(
        "/** Auto-generated by tools/export_world_map.py from World_map.xlsx — do not edit by hand. "
        "Playable y: 0..height-1 (margin rows in Excel are not exported). */"
    )
    js.append("(function (global) {")
    js.append("  const WIDTH = %d;" % width)
    js.append("  const HEIGHT = %d;" % height)
    js.append("  const BIOME_INDEX = new Uint8Array(%s);" % json.dumps(flat))
    js.append("  const CITY_NAMES = %s;" % json.dumps(city_names, ensure_ascii=True))
    js.append(
        "  global.WORLD_MAP_DATA = { width: WIDTH, height: HEIGHT, biomeIndex: BIOME_INDEX, cityNames: CITY_NAMES };"
    )
    js.append("})(typeof window !== \"undefined\" ? window : globalThis);")

    OUT.write_text("\n".join(js), encoding="utf-8")
    print("Wrote", OUT, "bytes", OUT.stat().st_size)
    print("biomes", len(biome_rows))
    for b in biome_rows:
        print(" ", b["idx"], b["hex"], b["name"], "passable" if b["passable"] else "BLOCK")


if __name__ == "__main__":
    main()
